### ISSUE TITLE
error in generating figures with diHMM

### ISSUE THREAD

**Issue by brini123** [gcyuan/diHMM#2]
Hello,

I recently installed dim on my mac laptop. I installed ghoshtscript and pdf and can generate figures without any trouble. But when I installed the same tools on my mac desktop I get the following error - 
_Reference to non-existent field 'XLim'.
![coverage](https://cloud.githubusercontent.com/assets/9453441/24634489/32ed6b40-189c-11e7-94af-111ce79310ed.jpg)

Error in cbfreeze (line 297)
   XLim = cb_prop.XLim;

Error in calculateBasicModelStatistics (line 109)
cbfreeze(HCB)_ 

While debugging for the issue, I checked that Xlim is not there under the cb_prob structure when I run on desktop, but it is present when I run the code on mac laptop.
I can only see the first figure - coverage but that too is distorted. 

My guess is there is some problem in locating the two tools - ghostscript and xpdf. I compared the folder structure of two diHMM files, it is the same. But I cannot figure out what is causing the script to fail on the desktop. Can someone please help me?

Thank you,
Sharmi

**Comment by gcyuan** [comment]
Hi,

This sounds like a Matlab issue rather than directly related to diHMM. I suggest you check online Matlab sources regarding the usage of XLim.

Best,
GC

**Comment by eugeniomarco** [comment]
Hi Sharmi,

With that information, it's a bit difficult to figure out the cause, especially since the code works on some machines and doesn't on others.

The problem arises when cbfreeze tries to get information about the axis. I'm not sure why, but on your desktop the colorbar axis has some issues. Are you sure you are plotting exactly the same model? Would it be possible for you to send the mat file with the model? I could then try to make the plots and see if I can reproduce the bug.

Thanks,
Eugenio

**Comment by brini123** [comment]
I am trying to debug for problems with MATLAB issues on my desktop.
I have attached the model files. It is the same one that I am trying on my laptop and that works. 

I really hope this problem is solved!

Thank you very much,
Sharmi


[Archive.zip](https://github.com/gcyuan/diHMM/files/900255/Archive.zip)

**Comment by gcyuan** [comment]
Hi Sharmi, could you let us know if your problem with running MATLAB has already been solved using the above suggestions?

**Comment by brini123** [comment]
Hi,

I am very sorry for the late reply.  The problem is solved.

Thank you,
Sharmi

**Comment by gcyuan** [comment]
Great. Thank you for using diHMM.
